[%
var gs: DagSet := DagSet.allInstances().at(0);
var makeString: String;
var i:Integer=1;
for (dag in gs.dagCollection){ 
	makeString=makeString+"syntethicTask"+i+".c ";
	i++;
}
%]
MAINSRCS = main.c
CSRCS = [%=makeString%]

CFLAGS= -DTOTAL_TASK=[%=i-1%] -O0 -g3
LDFLAGS=

#DOTSRCS= def.dot ciao.dot

BACKEND=./config/pthread_runtime
#BACKEND=./config/bostan-gomp
#recuperare dal config

#????
SCHEDULE=global

include $(BACKEND)/Makefile.hgr












