/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hipert.hg.gui;

import java.awt.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedList;

import javax.swing.AbstractButton;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JOptionPane;

import com.upscale.PsocMapper;

import hipert.hg.Globals;
import hipert.hg.XMLParser.DAG;
import hipert.hg.XMLParser.Node;
import hipert.hg.XMLParser.XMLGenerator;
import hipert.hg.XMLParser.XMLModifier;
import hipert.hg.modelToCode.DagToCode;
import hipert.hg.modelToCode.DagToCodeBostanGomp;

/**
 *
 * @author LPC
 */
public class hgGUI extends javax.swing.JFrame {
	

    /**
     * Creates new form NewJFrame
     */
    public hgGUI() {
        initComponents();    
        setPanelLoadDAGComponents();
    }
  
    public void setPanelLoadDAGComponents(){
    	ImageIcon imgIcon,imgHeader;
    	imgIcon = new ImageIcon("./imgs/icon_hipert.png");
		imgHeader = new ImageIcon("./imgs/logo_hipert2.png");
		this.setIconImage(imgIcon.getImage());
		this.setTitle("HipertLab Code generator");
		labelIconHeader.setIcon(imgHeader);
		
        rbPrem.setActionCommand("prem");
        rbSparse.setActionCommand("sparse");
        rbSequential.setActionCommand("sequential");
        rbRandom.setActionCommand("random");

        
    	txtOutput.setText(Globals.defaultOutputDir); 
    	txtRuntime.setText(Globals.defaultRuntimeDir);
    	txtGraphviz.setText(Globals.defaultGraphvizDir); 
    	
		ActionListener enablerListener = new ActionListener() {
			public void actionPerformed(ActionEvent actionEvent) {
				AbstractButton aButton = (AbstractButton) actionEvent.getSource();
				rbRandom.setEnabled(aButton.getText()=="Sparse" ? true : false);
				rbSequential.setEnabled(aButton.getText()=="Sparse" ? true : false);
				lblStride.setEnabled(aButton.getText()=="Sparse" ? true : false);
				lblStep.setEnabled(aButton.getText()=="Sparse" ? true : false);
				cbStride.setEnabled(aButton.getText()=="Sparse" ? true : false);
			}
	    };
		rbSparse.addActionListener(enablerListener);
		rbPrem.addActionListener(enablerListener);
		
		ActionListener enablerListener2 = new ActionListener() {
			public void actionPerformed(ActionEvent actionEvent) {
				AbstractButton aButton = (AbstractButton) actionEvent.getSource();
				cbStride.setEnabled(aButton.getText()=="Sequential" ? true : false);
			}
	    };
		rbSequential.addActionListener(enablerListener2);
		rbRandom.addActionListener(enablerListener2);

        //txtSparse only numbers
        /*txtSparse.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
              char c = e.getKeyChar();
              if (!((c >= '0') && (c <= '9') && (txtSparse.getText().length()<2) ||
                 (c == KeyEvent.VK_BACK_SPACE) ||
                 (c == KeyEvent.VK_DELETE))) {
                getToolkit().beep();
                e.consume();
              }
            }
          });*/
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupMemAccess = new javax.swing.ButtonGroup();
        groupSparse = new javax.swing.ButtonGroup();
        jTextField6 = new javax.swing.JTextField();
        tabPanel = new javax.swing.JTabbedPane();
        panteDagGenerator = new javax.swing.JPanel();
        panelElementsTab1 = new javax.swing.JPanel();
        bGenerateDag = new javax.swing.JButton();
        lstDagGenerated = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        panelTextFields = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        panelTabModify = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDagModify = new javax.swing.JList<>();
        bLoadToModify = new javax.swing.JButton();
        txtPeriod = new javax.swing.JTextField();
        txtDeadline = new javax.swing.JTextField();
        txtPriority = new javax.swing.JTextField();
        txtMap = new javax.swing.JTextField();
        txtMIET = new javax.swing.JTextField();
        txtMEET = new javax.swing.JTextField();
        txtMAET = new javax.swing.JTextField();
        txtMEM = new javax.swing.JTextField();
        cbMemUnit = new javax.swing.JComboBox<>();
        bApplyChanges = new javax.swing.JButton();
        labelDagModify = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panelCodeGenerator = new javax.swing.JPanel();
        scrollDagLoad = new javax.swing.JScrollPane();
        lstDagLoaded = new javax.swing.JList<>();
        bLoadDag = new javax.swing.JButton();
        bGenerateCode = new javax.swing.JButton();
        panelRadioButtons = new javax.swing.JPanel();
        rbPrem = new javax.swing.JRadioButton();
        rbSparse = new javax.swing.JRadioButton();
        bApplyMemAccess = new javax.swing.JButton();
        cbMemStep = new javax.swing.JComboBox<>();
        lblStep = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbSequential = new javax.swing.JRadioButton();
        rbRandom = new javax.swing.JRadioButton();
        cbStride = new javax.swing.JComboBox<>();
        lblStride = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstReadyDAG = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cbScheduling = new javax.swing.JComboBox<>();
        cbPartitioning = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblOutput = new javax.swing.JLabel();
        lblRuntime = new javax.swing.JLabel();
        lblGraphviz = new javax.swing.JLabel();
        txtRuntime = new javax.swing.JTextField();
        txtOutput = new javax.swing.JTextField();
        txtGraphviz = new javax.swing.JTextField();
        bOutput = new javax.swing.JButton();
        bRuntime = new javax.swing.JButton();
        bGraphviz = new javax.swing.JButton();
        labelIconHeader = new javax.swing.JLabel();

        jTextField6.setText("jTextField6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabPanel.setPreferredSize(new java.awt.Dimension(695, 364));

        panteDagGenerator.setPreferredSize(new java.awt.Dimension(695, 279));

        bGenerateDag.setText("Generate DAG");

        lstDagGenerated.setViewportView(jList1);

        jTextField1.setColumns(8);

        jTextField3.setColumns(8);

        jTextField5.setColumns(8);

        jTextField2.setColumns(8);

        jTextField4.setColumns(8);

        jTextField8.setColumns(8);

        jTextField9.setColumns(8);

        jTextField10.setColumns(8);

        jTextField11.setColumns(8);

        javax.swing.GroupLayout panelTextFieldsLayout = new javax.swing.GroupLayout(panelTextFields);
        panelTextFields.setLayout(panelTextFieldsLayout);
        panelTextFieldsLayout.setHorizontalGroup(
            panelTextFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTextFieldsLayout.createSequentialGroup()
                .addGroup(panelTextFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTextFieldsLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(panelTextFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTextFieldsLayout.createSequentialGroup()
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelTextFieldsLayout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelTextFieldsLayout.createSequentialGroup()
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelTextFieldsLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(panelTextFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTextFieldsLayout.createSequentialGroup()
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelTextFieldsLayout.createSequentialGroup()
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addComponent(jSeparator1)
        );
        panelTextFieldsLayout.setVerticalGroup(
            panelTextFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTextFieldsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTextFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTextFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTextFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelTextFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelElementsTab1Layout = new javax.swing.GroupLayout(panelElementsTab1);
        panelElementsTab1.setLayout(panelElementsTab1Layout);
        panelElementsTab1Layout.setHorizontalGroup(
            panelElementsTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelElementsTab1Layout.createSequentialGroup()
                .addGroup(panelElementsTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelElementsTab1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bGenerateDag, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))
                    .addGroup(panelElementsTab1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelTextFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(lstDagGenerated, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelElementsTab1Layout.setVerticalGroup(
            panelElementsTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelElementsTab1Layout.createSequentialGroup()
                .addGroup(panelElementsTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelElementsTab1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelTextFields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(bGenerateDag, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lstDagGenerated))
                .addContainerGap())
        );

        javax.swing.GroupLayout panteDagGeneratorLayout = new javax.swing.GroupLayout(panteDagGenerator);
        panteDagGenerator.setLayout(panteDagGeneratorLayout);
        panteDagGeneratorLayout.setHorizontalGroup(
            panteDagGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelElementsTab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panteDagGeneratorLayout.setVerticalGroup(
            panteDagGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelElementsTab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabPanel.addTab("DAG Generator", panteDagGenerator);

        lstDagModify.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstDagModify.setSelectionBackground(new java.awt.Color(102, 255, 255));
        lstDagModify.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(lstDagModify);

        bLoadToModify.setText("Load DAG");
        bLoadToModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoadToModifyActionPerformed(evt);
            }
        });

        txtPeriod.setColumns(8);

        txtDeadline.setColumns(8);

        txtPriority.setColumns(8);

        txtMap.setColumns(8);

        txtMIET.setColumns(8);

        txtMEET.setColumns(8);

        txtMAET.setColumns(8);

        txtMEM.setColumns(8);

        cbMemUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B", "KB", "MB" }));

        bApplyChanges.setText("Apply Changes");
        bApplyChanges.setEnabled(false);
        bApplyChanges.setMaximumSize(new java.awt.Dimension(79, 23));
        bApplyChanges.setMinimumSize(new java.awt.Dimension(79, 23));

        jLabel2.setText("Period");

        jLabel3.setText("Dedadline");

        jLabel4.setText("Priority");

        jLabel5.setText("Core map");

        jLabel6.setText("MIET");

        jLabel7.setText("MEET");

        jLabel8.setText("MAET");

        jLabel9.setText("MEM");

        jLabel10.setText("DAG Properties");

        jLabel11.setText("Node properties");

        javax.swing.GroupLayout panelTabModifyLayout = new javax.swing.GroupLayout(panelTabModify);
        panelTabModify.setLayout(panelTabModifyLayout);
        panelTabModifyLayout.setHorizontalGroup(
            panelTabModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabModifyLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(labelDagModify)
                .addGap(148, 760, Short.MAX_VALUE))
            .addGroup(panelTabModifyLayout.createSequentialGroup()
                .addGroup(panelTabModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTabModifyLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTabModifyLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(bLoadToModify, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(panelTabModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabModifyLayout.createSequentialGroup()
                        .addGroup(panelTabModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabModifyLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabModifyLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabModifyLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabModifyLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(26, 26, 26)
                        .addGroup(panelTabModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTabModifyLayout.createSequentialGroup()
                                .addGroup(panelTabModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelTabModifyLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtMIET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelTabModifyLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtMEET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelTabModifyLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtMAET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelTabModifyLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtMEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbMemUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelTabModifyLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel11)))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabModifyLayout.createSequentialGroup()
                        .addComponent(bApplyChanges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201))))
        );
        panelTabModifyLayout.setVerticalGroup(
            panelTabModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabModifyLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelDagModify)
                .addGroup(panelTabModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTabModifyLayout.createSequentialGroup()
                        .addGroup(panelTabModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(panelTabModifyLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(panelTabModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMIET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(panelTabModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMEET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(panelTabModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMAET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(panelTabModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbMemUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(0, 85, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelTabModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bLoadToModify)
                            .addComponent(bApplyChanges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelTabModifyLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(panelTabModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(26, 26, 26)
                        .addGroup(panelTabModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(panelTabModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(panelTabModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(panelTabModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tabPanel.addTab("Modify DAG", panelTabModify);

        lstDagLoaded.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstDagLoaded.setSelectionBackground(new java.awt.Color(102, 255, 255));
        lstDagLoaded.setSelectionForeground(new java.awt.Color(0, 0, 0));
        scrollDagLoad.setViewportView(lstDagLoaded);

        bLoadDag.setText("Load DAG Files");
        bLoadDag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoadDagActionPerformed(evt);
            }
        });

        bGenerateCode.setText("Generate Code");
        bGenerateCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGenerateCodeActionPerformed(evt);
            }
        });

        panelRadioButtons.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        groupMemAccess.add(rbPrem);
        rbPrem.setSelected(true);
        rbPrem.setText("PREM");
        rbPrem.setActionCommand("");

        groupMemAccess.add(rbSparse);
        rbSparse.setText("Sparse");
        rbSparse.setActionCommand("");

        bApplyMemAccess.setText("Apply");
        bApplyMemAccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bApplyMemAccessActionPerformed(evt);
            }
        });

        cbMemStep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "char", "int", "double", "long double" }));
        cbMemStep.setMinimumSize(new java.awt.Dimension(43, 22));
        cbMemStep.setPreferredSize(new java.awt.Dimension(43, 22));

        lblStep.setText("Step");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        groupSparse.add(rbSequential);
        rbSequential.setSelected(true);
        rbSequential.setText("Sequential");
        rbSequential.setEnabled(false);

        groupSparse.add(rbRandom);
        rbRandom.setText("Random");
        rbRandom.setEnabled(false);

        cbStride.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "4", "8", "16", "32", "64", "128", "256" }));
        cbStride.setEnabled(false);

        lblStride.setText("Stride");
        lblStride.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbSequential)
                        .addGap(18, 18, 18)
                        .addComponent(lblStride)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbStride, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rbRandom))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStride)
                    .addComponent(cbStride, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbSequential, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbRandom)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelRadioButtonsLayout = new javax.swing.GroupLayout(panelRadioButtons);
        panelRadioButtons.setLayout(panelRadioButtonsLayout);
        panelRadioButtonsLayout.setHorizontalGroup(
            panelRadioButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRadioButtonsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(rbPrem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(panelRadioButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelRadioButtonsLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(rbSparse)
                        .addGap(40, 40, 40)
                        .addComponent(lblStep)
                        .addGap(18, 18, 18)
                        .addComponent(cbMemStep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRadioButtonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bApplyMemAccess)
                .addGap(161, 161, 161))
        );
        panelRadioButtonsLayout.setVerticalGroup(
            panelRadioButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadioButtonsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelRadioButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPrem)
                    .addComponent(rbSparse)
                    .addComponent(cbMemStep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bApplyMemAccess))
        );

        lstReadyDAG.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(lstReadyDAG);

        jLabel1.setText("Ready Dags");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cbScheduling.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SCHED_FIFO", "SCHED_RR", "SCHED_OTHER" }));

        cbPartitioning.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GLOBAL", "PARTITIONED" }));

        jLabel12.setText("Scheduling algorithm");

        jLabel13.setText("Partitioning policy");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbScheduling, 0, 131, Short.MAX_VALUE)
                    .addComponent(cbPartitioning, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbScheduling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cbPartitioning))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCodeGeneratorLayout = new javax.swing.GroupLayout(panelCodeGenerator);
        panelCodeGenerator.setLayout(panelCodeGeneratorLayout);
        panelCodeGeneratorLayout.setHorizontalGroup(
            panelCodeGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCodeGeneratorLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(bLoadDag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bGenerateCode)
                .addGap(146, 146, 146))
            .addGroup(panelCodeGeneratorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCodeGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollDagLoad, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(panelCodeGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2)
                    .addComponent(panelRadioButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelCodeGeneratorLayout.setVerticalGroup(
            panelCodeGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCodeGeneratorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCodeGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelCodeGeneratorLayout.createSequentialGroup()
                        .addComponent(panelRadioButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCodeGeneratorLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrollDagLoad)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCodeGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGenerateCode, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLoadDag, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPanel.addTab("Code Generator", panelCodeGenerator);

        lblOutput.setText("Output Folder");

        lblRuntime.setText("Runtime Path");

        lblGraphviz.setText("Graphviz Path");

        txtRuntime.setEditable(false);
        txtRuntime.setBackground(new java.awt.Color(255, 255, 255));
        txtRuntime.setText("None");

        txtOutput.setEditable(false);
        txtOutput.setBackground(new java.awt.Color(255, 255, 255));
        txtOutput.setText("None");

        txtGraphviz.setEditable(false);
        txtGraphviz.setBackground(new java.awt.Color(255, 255, 255));
        txtGraphviz.setText("None");

        bOutput.setText("Load");
        bOutput.setName("loadFolder"); // NOI18N
        bOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOutputActionPerformed(evt);
            }
        });

        bRuntime.setText("Load");
        bRuntime.setName("loadRuntime"); // NOI18N
        bRuntime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRuntimeActionPerformed(evt);
            }
        });

        bGraphviz.setText("Load");
        bGraphviz.setName("loadGraphviz"); // NOI18N
        bGraphviz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGraphvizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblGraphviz)
                        .addGap(18, 18, 18)
                        .addComponent(txtGraphviz))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOutput)
                            .addComponent(lblRuntime))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtOutput)
                            .addComponent(txtRuntime, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bRuntime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bOutput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bGraphviz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOutput)
                    .addComponent(txtOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRuntime)
                    .addComponent(txtRuntime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bRuntime, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGraphviz)
                    .addComponent(txtGraphviz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bGraphviz, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(186, Short.MAX_VALUE))
        );

        tabPanel.addTab("Configuration", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelIconHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE))
                    .addComponent(tabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelIconHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(tabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /************************************************************PANEL GENERATE DAG***************************************************************/
 

	class applyGenerationHandler implements ActionListener {
		public void actionPerformed(ActionEvent e) {
			String memory_access = groupMemAccess.getSelection().getActionCommand();
			//System.out.println(lstDagLoaded.getModel().getElementAt(lstDagLoaded.getSelectedIndex()));
		}
	}
	
	class acceptGenerationHandler implements ActionListener {
		public void actionPerformed(ActionEvent e) {
			//JOptionPane.showMessageDialog(null, "Code Generated", "Code Generator", JOptionPane.INFORMATION_MESSAGE);
	        //new XMLGenerator(dagFiles,memory_access);
	        //new DagToCode();
			//setVisible(false);
		}
	}
	
    /*******************************************************************************************************************************************/

    /************************************************************PANEL MODIFY DAG***************************************************************/
	
	//BUTTON LOAD DAG TO MODIFY
    boolean firstLoad=true;
    MouseListener lastListener;
    XMLModifier xmlgen;
    File fileModify;
    @SuppressWarnings("unchecked")
	private void bLoadToModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoadToModifyActionPerformed
    	fileModify=MethodInterface.loadFile(this,false);
    	if(fileModify!=null){
    		xmlgen=new XMLModifier();
	        LinkedList<Node> nodes;
	        DAG dag=new DAG();

	        xmlgen.readDOTFile(fileModify.toString());
	        nodes=(LinkedList<Node>) xmlgen.getNodes().clone();
	        dag=xmlgen.getDag();
	    	@SuppressWarnings("rawtypes")
			DefaultListModel modelDagModify = new DefaultListModel();
	    	lstDagModify.setModel(modelDagModify);
	    	bApplyChanges.setEnabled(true);
	    	
	    	labelDagModify.setText(fileModify.getName());
	        for(Node node: nodes){
	        	modelDagModify.addElement("Node-"+node.getNodeID());
	        }
	        Integer period=dag.getPeriod();
	        Integer deadline=dag.getDeadline();
	        Integer priority=dag.getPriority();
	        Integer map=dag.getMap();
	    	txtPeriod.setText(period.toString());
	    	txtDeadline.setText(deadline.toString());
	    	txtPriority.setText(priority.toString());
	    	txtMap.setText(map.toString());
	    	if(firstLoad){
	    		firstLoad=false;
	    		lastListener=new listModifyListener(nodes);
		        lstDagModify.addMouseListener(lastListener);
	    	}else{
	    		lstDagModify.removeMouseListener(lastListener);
	    		lastListener=new listModifyListener(nodes);
		        lstDagModify.addMouseListener(lastListener);
	    	}
	    	
    	}   
    }//GEN-LAST:event_bLoadToModifyActionPerformed
    
    //LIST NODE TO MODIFY LISTENER
    private class listModifyListener implements MouseListener {
        private  LinkedList<Node> nodes;

        public listModifyListener(LinkedList<Node> nodesP) {
        	this.nodes=new LinkedList<Node>();
            this.nodes = (LinkedList<Node>) nodesP.clone();
        }
        
		@Override
        public void mouseClicked(MouseEvent evt) {
	        JList list = (JList)evt.getSource();
		    int index = list.locationToIndex(evt.getPoint());
		    if(index>=0){
			    index = list.locationToIndex(evt.getPoint());
		    	txtMIET.setText(String.valueOf(this.nodes.get(index).getWcet()));
		    	txtMEET.setText(String.valueOf(this.nodes.get(index).getIwcet()));
		    	txtMAET.setText(String.valueOf(this.nodes.get(index).getMaet()));
		    	txtMEM.setText(String.valueOf(this.nodes.get(index).getMem_access()));
		    	cbMemUnit.setSelectedItem(this.nodes.get(index).getMem_unit());
		    }
	    }

		@Override
		public void mouseEntered(MouseEvent e) {
			// TODO Auto-generated method stub
			
		}
		@Override
		public void mouseExited(MouseEvent e) {
			// TODO Auto-generated method stub
			
		}
		@Override
		public void mousePressed(MouseEvent e) {
			// TODO Auto-generated method stub
			
		}
		@Override
		public void mouseReleased(MouseEvent e) {
			// TODO Auto-generated method stub
			
		}
    }
    

    /*******************************************************************************************************************************************/

    /************************************************************PANEL GENERATE CODE************************************************************/
	
    //LOAD BUTTON LISTENER && LIST LISTENER
	private void bLoadDagActionPerformed(java.awt.event.ActionEvent evt) {                                         
        files=MethodInterface.loadFiles(this,true);
    	if(files!=null)
    		refreshDAGFiles(files,lstDagLoaded);

    	lstDagLoaded.addMouseListener(new MouseAdapter() {
		    public void mouseClicked(MouseEvent evt) {
		        JList list = (JList)evt.getSource();
			    int index = list.locationToIndex(evt.getPoint());
			    if(index>=0){
					if (evt.getClickCount() == 2) {
					    index = list.locationToIndex(evt.getPoint());
						new ImageDag("dagToPNG/"+list.getSelectedValue().toString().replace(".dot", ".png"));
					}
			    }
		    }
		});
    }
	
	//APPLY BUTTON MEMORY ACCESS
    DefaultListModel modelReadyDag = new DefaultListModel();
    @SuppressWarnings("unchecked")
	private void bApplyMemAccessActionPerformed(java.awt.event.ActionEvent evt) {      
		if(lstDagLoaded.getSelectedIndex()<0){
			JOptionPane.showMessageDialog(null, "Choose a DAG", "Code Generated", JOptionPane.INFORMATION_MESSAGE);
		}else{
			String memory_access = groupMemAccess.getSelection().getActionCommand();
			String memory_stride = groupSparse.getSelection().getActionCommand();
	    	lstReadyDAG.setModel(modelReadyDag);
	    	if(memory_access=="prem"){
	    		modelReadyDag.addElement(lstDagLoaded.getSelectedValue().toString()+Globals.Separator+memory_access+Globals.Separator+cbMemStep.getSelectedItem().toString());
	    	}
	    	else if (memory_access=="sparse"){
	    		if(memory_stride=="random")
	    			modelReadyDag.addElement(lstDagLoaded.getSelectedValue().toString()+Globals.Separator+memory_access+Globals.Separator+cbMemStep.getSelectedItem().toString()+
	    				 Globals.Separator + memory_stride);
	    		else
	    			modelReadyDag.addElement(lstDagLoaded.getSelectedValue().toString()+Globals.Separator+memory_access+Globals.Separator+cbMemStep.getSelectedItem().toString()+
	    				 Globals.Separator + memory_stride + Globals.Separator+cbStride.getSelectedItem().toString());
	    	}
		}
    }
    XMLGenerator xmlGenerator = null;
    File[] files = null;

    //GENERATE CODE BUTTON
    private void bGenerateCodeActionPerformed(java.awt.event.ActionEvent evt) {                                              
    	if(lstReadyDAG.getModel().getSize()<=0){
			JOptionPane.showMessageDialog(null, "There is no any DAG loaded", "Code Generated", JOptionPane.INFORMATION_MESSAGE);
    	}else{
    		
    		xmlGenerator = new XMLGenerator(packDags());

			DagToCode codeGenerator = null;
			if(false)
				codeGenerator = new DagToCode();
			else
				codeGenerator = new DagToCodeBostanGomp();
			
			ArrayList<String> fileNames = new ArrayList<String>();
			try
			{
				for (File file : files) {
					fileNames.add(file.getCanonicalPath());
				}
				Globals.GenFilesDir=txtOutput.getText();
				codeGenerator.GenerateCode(fileNames);
		        JOptionPane.showMessageDialog(null, "Code Generated", "Code Generator", JOptionPane.INFORMATION_MESSAGE);
			}
			catch(Exception ex) {
		        JOptionPane.showMessageDialog(null, ex.getMessage(), "Code Generator", JOptionPane.ERROR_MESSAGE);			
			}
			
    	}
    }
    
    //THIS FUNCTION PREPARES THE MODEL 
	private DAG[] packDags() {
		DAG dags[] = new DAG[lstReadyDAG.getModel().getSize()];
		for(int i=0;i<lstReadyDAG.getModel().getSize();i++){
			String filePath="dags/"+lstReadyDAG.getModel().getElementAt(i).split(Globals.Separator)[0];
			String mem_access=lstReadyDAG.getModel().getElementAt(i).split(Globals.Separator)[1];
			String sched_policy=cbScheduling.getSelectedItem().toString();
			String output_dir=txtOutput.getText();
			String partitioning_policy=cbPartitioning.getSelectedItem().toString();
			//memory access type
			if(mem_access.equals("prem")){
				String stepString=lstReadyDAG.getModel().getElementAt(i).split(Globals.Separator)[2];
				int step=calcStep(stepString);
				dags[i]=new DAG(filePath,mem_access,step,sched_policy,partitioning_policy,output_dir);
			}
			else if (mem_access.equals("sparse")){
				String stepString=lstReadyDAG.getModel().getElementAt(i).split(Globals.Separator)[2];
				int step=calcStep(stepString);
				
				//Stride access type
				String strideType=lstReadyDAG.getModel().getElementAt(i).split(Globals.Separator)[3];
				int stride=0; //random access
				if(strideType.equals("sequential")){
					stride=Integer.parseInt(lstReadyDAG.getModel().getElementAt(i).split(Globals.Separator)[4]);
				}
				dags[i]=new DAG(filePath,mem_access,step,stride,sched_policy,partitioning_policy,output_dir);
			}
		}
		return dags;
	}
	
	private int calcStep(String stepString) {
		//step access type
		int step=0;
		if (stepString.equals("char")){
			step=1; //bits
		}else if(stepString.equals("int")){
			step=4;
		}else if(stepString.equals("double")){
			step=8;
		}else if(stepString.equals("long double")){
			step=16;
		}
		return step;
	}

	//FUNCTION TO REFRESH AVAILABLE DAGS
    @SuppressWarnings("unchecked")
	private void refreshDAGFiles(File[] files,JList lst) {
		@SuppressWarnings("rawtypes")
		DefaultListModel model = new DefaultListModel();
    	lst.removeAll();
    	lst.setModel(model);
    	for(File f : files){
            model.addElement(f.getName());
		    Runtime rt = Runtime.getRuntime();
			try {
				Process pr = rt.exec(txtGraphviz.getText()+"bin/dot.exe "
				+ "-Tpng dags/"+f.getName()
				+ " -o dagToPNG/"+f.getName().toString().replace(".dot", ".png"));
			} catch (IOException e) {
				//e.printStackTrace();
				// For some reason it fails (e.g., no graphviz installed). Not fatal..
			}
    	}
    }
    
    /*******************************************************************************************************************************************/
    
    /************************************************************PANEL CONFIGURATION************************************************************/

    private void bOutputActionPerformed(java.awt.event.ActionEvent evt) {
        File file=MethodInterface.loadFolder(this,false);
        if(file!=null)
        	txtOutput.setText(file.getPath());
    }

    private void bRuntimeActionPerformed(java.awt.event.ActionEvent evt) {    

        File file=MethodInterface.loadFolder(this,false);
        if(file!=null)
        	txtRuntime.setText(file.getPath());
    }

    private void bGraphvizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGraphvizActionPerformed
        File file=MethodInterface.loadFolder(this,false);
        if(file!=null)
        	txtGraphviz.setText(file.getPath()); 
    }//GEN-LAST:event_bGraphvizActionPerformed
    /*******************************************************************************************************************************************/

	/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hgGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hgGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hgGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hgGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hgGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bApplyChanges;
    private javax.swing.JButton bApplyMemAccess;
    private javax.swing.JButton bGenerateCode;
    private javax.swing.JButton bGenerateDag;
    private javax.swing.JButton bGraphviz;
    private javax.swing.JButton bLoadDag;
    private javax.swing.JButton bLoadToModify;
    private javax.swing.JButton bOutput;
    private javax.swing.JButton bRuntime;
    private javax.swing.JComboBox<String> cbMemStep;
    private javax.swing.JComboBox<String> cbMemUnit;
    private javax.swing.JComboBox<String> cbPartitioning;
    private javax.swing.JComboBox<String> cbScheduling;
    private javax.swing.JComboBox<String> cbStride;
    private javax.swing.ButtonGroup groupMemAccess;
    private javax.swing.ButtonGroup groupSparse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel labelDagModify;
    private javax.swing.JLabel labelIconHeader;
    private javax.swing.JLabel lblGraphviz;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JLabel lblRuntime;
    private javax.swing.JLabel lblStep;
    private javax.swing.JLabel lblStride;
    private javax.swing.JScrollPane lstDagGenerated;
    private javax.swing.JList<String> lstDagLoaded;
    private javax.swing.JList<String> lstDagModify;
    private javax.swing.JList<String> lstReadyDAG;
    private javax.swing.JPanel panelCodeGenerator;
    private javax.swing.JPanel panelElementsTab1;
    private javax.swing.JPanel panelRadioButtons;
    private javax.swing.JPanel panelTabModify;
    private javax.swing.JPanel panelTextFields;
    private javax.swing.JPanel panteDagGenerator;
    private javax.swing.JRadioButton rbPrem;
    private javax.swing.JRadioButton rbRandom;
    private javax.swing.JRadioButton rbSequential;
    private javax.swing.JRadioButton rbSparse;
    private javax.swing.JScrollPane scrollDagLoad;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JTextField txtDeadline;
    private javax.swing.JTextField txtGraphviz;
    private javax.swing.JTextField txtMAET;
    private javax.swing.JTextField txtMEET;
    private javax.swing.JTextField txtMEM;
    private javax.swing.JTextField txtMIET;
    private javax.swing.JTextField txtMap;
    private javax.swing.JTextField txtOutput;
    private javax.swing.JTextField txtPeriod;
    private javax.swing.JTextField txtPriority;
    private javax.swing.JTextField txtRuntime;
    // End of variables declaration//GEN-END:variables
}